### ISSUE TITLE
Package not available for R 3.5.3

### ISSUE THREAD

**Issue by gauravrpjain** [mrpsonglao/WBdata360R#3]
The R package on CRAN is not available for R 3.5.3. Also, the 3 packages used in the repo have updated versions: 
1. data.table (current: 1.12.0) -> latest: 1.12.6
2. curl (current: 3.3) -> latest: 4.3
3. Rcpp (current 1.0.1) -> latest: 1.0.3

**Comment by pechiyappan** [comment]
Hello,

Can you follow the steps here and check if it can be resolved? I checked with other versions of R and faced no issues with installation.

https://stackoverflow.com/questions/25721884/how-should-i-deal-with-package-xxx-is-not-available-for-r-version-x-y-z-wa

Thanks!
