### ISSUE TITLE
Overall Global Gender Gap Index

### ISSUE THREAD

**Issue by msgoussi** [mrpsonglao/WBdata360R#4]
Hi... 
I can not find "Overall Global Gender Gap Index", and it is not updated by recent values at TCdata360.
Please advis.e

**Comment by pechiyappan** [comment]
Hello msgoussi,

Please find the most recent data [here](https://tcdata360.worldbank.org/indicators/af52ebe9?country=BRA&indicator=27962&viz=line_chart&years=2006,2021)
